name: release

on:
    create:
        tags:
            - v*

jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        steps:
            - 
                name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.14

            -
                name: "Check out code"
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -
                name: Get dependencies 
                run: |
                    go get -v -t -d ./...
                    if [ -f Gopkg.toml ]; then
                        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
                        dep ensure
                    fi

            -
                name: "Create release on GitHub"
                uses: goreleaser/goreleaser-action@v2
                env:
                    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                with:
                    args: "release --rm-dist"
                    version: latest
